// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[title].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/post.ts";
import * as $3 from "./routes/api/posts.ts";
import * as $4 from "./routes/components.tsx";
import * as $5 from "./routes/dashboard.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/new.tsx";
import * as $$0 from "./islands/DashBoardPosts.tsx";
import * as $$1 from "./islands/DashboardEditPost.tsx";
import * as $$2 from "./islands/DashboardMyself.tsx";
import * as $$3 from "./islands/DashboardPage.tsx";
import * as $$4 from "./islands/Dropdown.tsx";
import * as $$5 from "./islands/NewPage.tsx";
import * as $$6 from "./islands/SearchPage.tsx";
import * as $$7 from "./islands/SidebarMenu.tsx";
import * as $$8 from "./islands/TagsSelector.tsx";
import * as $$9 from "./islands/Textbox.tsx";

const manifest = {
  routes: {
    "./routes/[title].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/post.ts": $2,
    "./routes/api/posts.ts": $3,
    "./routes/components.tsx": $4,
    "./routes/dashboard.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/new.tsx": $7,
  },
  islands: {
    "./islands/DashBoardPosts.tsx": $$0,
    "./islands/DashboardEditPost.tsx": $$1,
    "./islands/DashboardMyself.tsx": $$2,
    "./islands/DashboardPage.tsx": $$3,
    "./islands/Dropdown.tsx": $$4,
    "./islands/NewPage.tsx": $$5,
    "./islands/SearchPage.tsx": $$6,
    "./islands/SidebarMenu.tsx": $$7,
    "./islands/TagsSelector.tsx": $$8,
    "./islands/Textbox.tsx": $$9,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
